name: âœ¨ Code Quality Check
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ğŸ§¶ ESLint
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¥ Download deps
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: ğŸ§¶ Lint
        run: pnpm lint

  typecheck:
    name: ğŸ”¬ TypeScript
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¥ Download deps
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: ğŸ”¬ Type check
        run: pnpm typecheck

  vitest:
    name: âš¡ Vitest
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¥ Download deps
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: âš¡ Run vitest
        run: pnpm test:coverage

  format:
    name: ğŸ“ Format
    runs-on: ubuntu-22.04
    steps:
      - name: ğŸ‘€ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: ğŸ“¥ Download deps
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: true

      - name: ğŸ“ Format
        run: pnpm format:check
